apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamesfront--deployment
  labels:
    app: gamesfront
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gamesfront
  template:
    metadata:
      labels:
        app: gamesfront
    spec:
      containers:
      - name: gamesfront
        image: {{ .Values.image.repository1 }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000

