name: Java CI with Maven

on:
  push:
    paths-ignore:
          - 'Read.md'
          - '.github/*'
          - 'helm/*'
    branches:
      - main
          
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
     # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
     #
  #push_to_docker_hub:
  #  runs-on: ubuntu-latest

  #  needs: build

   # steps:
  #  - name: Checkout repository
  #    uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
         username: ${{ secrets.DOCKER_USEERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USEERNAME }}/gamesfront:${{github.run_id}}
        
    
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/gamesfront_chart/values.yaml
    #- name: Commit and push changes
     # run: |
      #  git config --global user.email "araheemcis@gmail.com"
       # git config --global user.name "Abdul Raheem"
        #git add helm/calculator_chart/values.yaml
        #git commit -m "Update tag in Helm chart"
        #git push
    

    - name: Commit and push changes
      run: |
        git config --global user.email "araheemcis@gmail.com"
        git config --global user.name "Abdul Raheem"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push   

        #

  
   
      
